server:
  port: 9002
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  profiles:  
    active: dev
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  messages:
    basename: com/ikeyit/common/errors,messages
    encoding: UTF-8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: your_mysql_username
    password: your_mysql_password
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/auth/jwks

rocketmq:
  name-server: localhost:9876
  producer:
    group: group-trade

#配置ribbon不经过服务注册中心直接访问对应服务
passport-service:
  ribbon:
    listOfServers: localhost:9000
product-service:
  ribbon:
    listOfServers: localhost:9001
